### ISSUE TITLE
More prompts could be made to made for LLM to perform better

### ISSUE THREAD

**Issue by utsabsamadder** [TusharAMD/SuperSpeechSaga#10]
With more prompts, the LLM's knowledge base will increase and its performance under various scenarios will improve. I would like to  do this and take part in GSSoC'24

**Comment by Geetika2274** [comment]
I have LLM knowledge and want to show case my skills. 
Approach: prompts based on performance feedback. 
Briefly explained: 
1) One can effectively enhance the performance of the LLM model for specific task .One can  use a diverse range of prompts to cover different aspects of the task. This includes varying sentence structures, lengths, and formats.
2) Contextual Prompts  provide information or cues that guide the model towards the desired output. This helps the model understand the task better and produce more accurate responses.

**Comment by TusharAMD** [comment]
Hello @utsabsamadder and @Geetika2274, we have definitely planned to add more prompts but they would be specific to game. And so the issues would be game specific. I would be soon adding detailed information in Readme section. Keep a look on issues or alternatively you can also come up with game ideas and add new issue saying you would be contributing to prompt of that particular game.
