### ISSUE TITLE
Adding a requirements.txt file

### ISSUE THREAD

**Issue by ShivamShrivastava18** [TusharAMD/SuperSpeechSaga#14]
Dear @TusharAMD ,
I would like to contribute to this project under GSSOC'24 by adding a requirements.txt file that can install required packages and libraries to run this project by only one command. I would also like to update this in the Readme.md file as well. It provides a consistent environment and makes collaboration easier hence allowing more people to contribute or try out this amazing project.
Thanks for considering my request.

**Comment by aaradhyasinghgaur** [comment]
Hey , @TusharAMD , i would like to add a requirement.txt file to this project for better understanding of packages/frameworks used throughout the project.
Full Name :- Aaradhya Singh , GSSOC-2024 (contributor)

**Kindly assign this issue to me**

**Comment by ananyabansal16** [comment]
If this issue is still pending, I can take this up under GSSoC'24. Lemme know. :)
