### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Aryan-Chharia** [TusharAMD/SuperSpeechSaga#3]
I recommend that we should add a code of conduct to this repo. @TusharAMD Can you assign this issue to me under GSSoC'24 ?

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by Aryan-Chharia** [comment]
Hi @TusharAMD , can assign gssoc24 label to this issue ?

**Comment by akshatsharma2407** [comment]
Hello, I am fully capable of updating your Code of conduct section as a GSSoC contributor. Kindly assign me this issue as I possess intermediate knowledge of the technology utilized in your project. I am confident that I am the best fit for this task.

**Comment by Aryan-Chharia** [comment]
Hi @TusharAMD i opened a pull request can you look into it?

**Comment by utsabsamadder** [comment]
I would like to work on this project under GSSoC'24
Could you please assign me to it?

**Comment by utsabsamadder** [comment]
Hi @Aryan-Chharia, I would like to work on this project under GSSoC'24
Could you please assign me to it?
