### ISSUE TITLE
Add: LICENSE File for Clarity and Contribution

### ISSUE THREAD

**Issue by mdazfar2** [TusharAMD/SuperSpeechSaga#34]
## Description
I noticed that this project currently doesn't have a LICENSE file.  Including a LICENSE file is important for several reasons:

- **Clarity for Users:** It clearly defines how users can use, modify, and distribute the project's code.
- **Encourages Contribution:** A LICENSE provides potential contributors with a legal framework for participating in the project.

I'd be happy to contribute a basic LICENSE file using a widely-used open-source license like MIT or Apache 2.0.  We can then discuss the most appropriate license for this project's needs.

## Benefits
- Increased clarity for users regarding code usage
- Encouragement for potential contributors
- Improved project transparency and professionalism

> I want to contribute on this project, Assign this issue to me @TusharAMD

**Comment by TusharAMD** [comment]
Right now we are not planning to add license actually. We would discuss and think which license to use. MIT license would give rights to everyone to redistribute these projects with monetary gain. Please check out other issues or make an issue of your own and start contributing.
