### ISSUE TITLE
Auto Commenting feature for PR Raised

### ISSUE THREAD

**Issue by Asymtode712** [TusharAMD/SuperSpeechSaga#38]
This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs. By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

**Comment by Asymtode712** [comment]
@TusharAMD  please assign me this issue under gssoc'24

**Comment by TusharAMD** [comment]
Can you please elaborate what will be the comment on raising a PR?

**Comment by Asymtode712** [comment]
![PR raised](https://github.com/TusharAMD/SuperSpeechSaga/assets/115717746/5c6c48fa-2d85-4309-be1e-6259aaec1421)

**Comment by TusharAMD** [comment]
Ok done

**Comment by Asymtode712** [comment]
@TusharAMD would you please add relevant level labels too
