### ISSUE TITLE
Auto Commenting feature for PR Merged

### ISSUE THREAD

**Issue by Asymtode712** [TusharAMD/SuperSpeechSaga#39]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

**Comment by Asymtode712** [comment]
@TusharAMD  please assign me this issue under gssoc'24

**Comment by TusharAMD** [comment]
done

**Comment by Asymtode712** [comment]
@TusharAMD would you please add relevant level labels too

**Comment by Asymtode712** [comment]
@TusharAMD would you please add relevant level labels too
