### ISSUE TITLE
Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [TusharAMD/SuperSpeechSaga#41]
This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

**Comment by Asymtode712** [comment]
@TusharAMD please assign me this issue under gssoc'24

**Comment by TusharAMD** [comment]
@Asymtode712 Done

**Comment by Asymtode712** [comment]
@TusharAMD would you please add relevant level labels too
