### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by aasthakourav20** [TusharAMD/SuperSpeechSaga#54]
What's missing in this repository!!

A README file is essential in any given repository because it serves as the primary source of information about the project. It provides an overview of the project's purpose, how to install and use it, and any necessary prerequisites. Additionally, the README often includes guidelines for contributing, links to documentation, and contact information for the maintainers. This file ensures that both new and returning users can easily understand the project's scope, setup, and usage, thereby enhancing the project's accessibility and fostering collaboration. By consolidating all critical information in one place, a README file significantly improves the user experience and facilitates effective project management.

Kindly assign this issue to me under GSSoC'24

**Comment by TusharAMD** [comment]
What are things missing from readme we have right now?

**Comment by aasthakourav20** [comment]
Hey @TusharAMD , we can add specific project features to the readme , helps the contributors to go through in single run rather than paragraphs . And I think Installation steps are incomplete and undescriptive  , all these things should be taken care in contributors point of view .

**Comment by TusharAMD** [comment]
Ok @aasthakourav20 assigned. but please don't remove the video link from the image. I would be uploading a video in few hours to get idea about project so start working on this issue after that.

**Comment by aasthakourav20** [comment]
> Ok @aasthakourav20 assigned. but please don't remove the video link from the image. I would be uploading a video in few hours to get idea about project so start working on this issue after that.

Sure !! Thank you
