### ISSUE TITLE
I am not able to run the app.py file

### ISSUE THREAD

**Issue by VijaySamant4368** [TusharAMD/SuperSpeechSaga#58]
I have installed all the necessary libraries, but it says:
FileNotFoundError: [Errno 2] No such file or directory: 'config_keys.json'
Please help

**Comment by TusharAMD** [comment]
Hi @VijaySamant4368 . Yes the code will not run without config_keys.json as it contains authentication keys for Gemini api. We have to use own api keys as keys cannot be uploaded on GitHub. There is free version of Google Gemini which you can find on aistudio. I will be updating a detailed doc on how to obtain the keys.

**Comment by VijaySamant4368** [comment]
Thank you very much.

**Comment by MimoHasPurpose** [comment]
Can you assign me this issue? @VijaySamant4368
