### ISSUE TITLE
Hyperlinks problem in the README.md

### ISSUE THREAD

**Issue by VijaySamant4368** [TusharAMD/SuperSpeechSaga#63]
In the README.md file, instead of the hyperlinks like:
[My text Here](MyLinkHere)

It is in the form of links:
[My text Here] MyLinkHere

Although this doesn't add anything practical, it makes the README.me file better to view

**Comment by sanskritiagr** [comment]
I can work on this.

**Comment by sanskritiagr** [comment]
Please assign it to me.

**Comment by TusharAMD** [comment]
@VijaySamant4368 assigned

**Comment by MimoHasPurpose** [comment]
can i get this issue, @VijaySamant4368 ?
