### ISSUE TITLE
NeonNoir - Shadows of the Cyber City

### ISSUE THREAD

**Issue by TusharAMD** [TusharAMD/SuperSpeechSaga#94]
![image](https://github.com/user-attachments/assets/f3ebb94d-7cc3-4263-8e6d-28dc137c17e1)

## Create a story based on the below description. This will act as base for further game dev

In NeonNoir, players step into the shoes of a private detective in a sprawling cyberpunk metropolis. Amidst neon lights and rain-soaked streets, they uncover a conspiracy that threatens the city's fragile balance. Through intense interrogations, hacking sequences, and action-packed encounters, players shape the story, making allies and enemies. This game fuses noir mystery, real-time dialogue, and action elements to create a gripping, immersive experience.

## How to begin

1. Fork and clone this repo to local machine
2. cd into the game directory 
3. Make your changes
4. Commit to a new branch and make pull request

**Comment by mahek0620** [comment]
@TusharAMD I am willing to work on this can you assign this to me
