### ISSUE TITLE
ChronoQuest - The Temporal Odyssey

### ISSUE THREAD

**Issue by TusharAMD** [TusharAMD/SuperSpeechSaga#95]
![image](https://github.com/user-attachments/assets/32960fd1-4424-49c0-8f34-e246e65e98f0)

## Create a story based on the below description. This will act as base for further game dev

ChronoQuest thrusts players into the role of a time-traveling adventurer tasked with preserving the timeline. As anomalies disrupt history, players navigate through various eras, from medieval kingdoms to futuristic cities. Every interaction and decision influences the unfolding narrative, creating a dynamic, ever-changing storyline. This game blends exploration, real-time dialogue, and strategic thinking to deliver an epic temporal journey.

## How to begin

1. Fork and clone this repo to local machine
2. cd into the game directory 
3. Make your changes
4. Commit to a new branch and make pull request

**Comment by mahek0620** [comment]
@TusharAMD I am willing to work on this can you assign this to me
